import json
# Load previously generated JSONs
with open("eps.json","r", encoding="UTF8") as f:
    EpisodeNames = json.load(f)
with open("episodec.json","r", encoding="UTF8") as f:
    Episodes = json.load(f)
with open("out.json","r", encoding="UTF8") as f:
    TVDescript = json.load(f)
# TV JSON is generated by the directory that your files are in.(directory_map.py)
with open("tv.json","r", encoding="UTF8") as f:
    TVData = json.load(f)
# Merge The Data
for year in TVData:
    for ep in TVData[year]:
        es = []
        rem = []
        ss = []
        try:
            for e in Episodes[str(int(ep["Episode"]))]:
                es.append(EpisodeNames[e][0])
                if EpisodeNames[e][1] == '動畫原創':
                    rem.append(False)
                else:
                    rem.append(EpisodeNames[e][1])
                try:
                    ss.append(TVDescript[e].replace("\n",""))
                except:
                    pass
        except Exception as e:
            print(e)
            es.append("Unknown Story")
        ep["storyName"] = es
        ep["isRemake"] = rem
        ep["keywords"] = ss
# Copy ntv.json to the main directory
with open("ntv.json","w",encoding="UTF8") as f:
    json.dump(TVData,f)
"""
Functionality:
- Loads the previous JSON files.
- Loops through the years and episodes in TVData.
- Gets the story names, isRemake values, and descriptions for an episode.
- Adds the merged data to the episode dictionary.
- Dumps the updated TVData to a JSON file called ntv.json.
"""